name: Convert Notebooks to HTML
on:
  push:
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install jupyter nbconvert beautifulsoup4
    
    - name: Convert notebooks maintaining structure
      run: |
        # Find and convert all notebooks maintaining structure
        for notebook in $(find . -name "*.ipynb" -not -path "./.git/*"); do
          # Get directory path
          dir=$(dirname "$notebook")
          # Create same structure in output folder
          mkdir -p "output/$dir"
          echo "Converting $notebook"
          jupyter nbconvert --to html "$notebook" --output-dir="output/$dir"
        done
    
    - name: Create index page
      run: |
        cat > output/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Data Science Portfolio</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
                    max-width: 900px;
                    margin: 0 auto;
                    padding: 20px;
                    background: #f5f5f5;
                }
                h1 {
                    color: #333;
                    border-bottom: 3px solid #4CAF50;
                    padding-bottom: 10px;
                }
                .notebook-list {
                    background: white;
                    border-radius: 8px;
                    padding: 20px;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                }
                .folder {
                    margin: 20px 0;
                }
                .folder-name {
                    font-weight: bold;
                    color: #2196F3;
                    margin-bottom: 10px;
                    font-size: 1.2em;
                }
                .notebook-link {
                    display: block;
                    padding: 10px;
                    margin: 5px 0;
                    background: #f8f9fa;
                    border-left: 4px solid #4CAF50;
                    text-decoration: none;
                    color: #333;
                    transition: all 0.3s;
                }
                .notebook-link:hover {
                    background: #e8f5e9;
                    transform: translateX(5px);
                }
                .path {
                    font-size: 0.9em;
                    color: #666;
                }
            </style>
        </head>
        <body>
            <h1>📊 Data Science Portfolio</h1>
            <div class="notebook-list">
        EOF
        
        # Create list of notebooks with structure
        echo "<h2>Notebooks</h2>" >> output/index.html
        
        # Group by folder
        last_dir=""
        find output -name "*.html" -not -name "index.html" | sort | while read file; do
          # Remove 'output/' from path
          rel_path=${file#output/}
          dir=$(dirname "$rel_path")
          basename=$(basename "$file" .html)
          
          # If it's a new folder, create section
          if [ "$dir" != "$last_dir" ]; then
            if [ "$last_dir" != "" ]; then
              echo "</div>" >> output/index.html
            fi
            echo "<div class='folder'>" >> output/index.html
            echo "<div class='folder-name'>📁 $dir</div>" >> output/index.html
            last_dir=$dir
          fi
          
          # Add link to notebook
          echo "<a href='$rel_path' class='notebook-link'>" >> output/index.html
          echo "  📓 $basename" >> output/index.html
          echo "  <span class='path'>($rel_path)</span>" >> output/index.html
          echo "</a>" >> output/index.html
        done
        
        echo "</div></div></body></html>" >> output/index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output